title: API Design Studio
description: 'Web-Based Open Source API Design via the OpenAPI specification.'
url: 'http://www.apidesigner.org'
version: 0.0.4
quickstart:
    tomcat_version: 0.0.4
twitter_username: APIDesignStudio
github_username: apiman
github_url: https://github.com/apiman/apiman-studio
email: apiman-user@lists.jboss.org
future: true
excerpt_separator: '---'
gems:
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-seo-tag
    - jemoji
sass:
    style: compressed
collections:
    docs: {output: true, permalink: '/docs/:path/'}
defaults:
    - {scope: {type: docs}, values: {layout: docs}}
    - {scope: {type: posts}, values: {layout: post, permalink: '/blog/:year/:month/:day/:title'}}
    - {scope: {path: ""}, values: {image: {path: /images/opengraph.png, width: 1200, height: 630}}}
exclude:
    - node_modules
    - README.md
    - LICENSE.md
    - CNAME
    - Gemfile
    - Gemfile.lock
    - Gruntfile.js
    - package.json
    - script
    - spec
include:
    - _pages
twitter:
    username: APIDesignStudio
logo: /images/opengraph.png
