baseurl = "http://studio.apiman.io/"
languageCode = "en-us"
title = "API Design Studio"
theme = "hugo-creative-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "JBoss APIMan API Design Studio"
	description = "An open source studio for designing REST based APIs using the OpenAPI specification."

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "APIMan Design Studio"

		[params.navigation.links]
			about     = "About"
			features  = "Features"
			portfolio = "Documentation"
			contact   = "Join Us!"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Open Source API Design"
		subtitle   = "Looking for a simple but powerful tool to collaboratively design REST APIs?  Well then, look no further!"
		buttonText = "Tell me more!"
		repo       = "https://github.com/apiman/apiman-studio"


	# About section
	[params.about]
		headline    = "We've got what you need!"
		description = "Whether you're designing a new REST API from scratch, or documenting one that's already in production, the API Design Studio has your back.  Collaborate with friends and colleagues to create the perfect API for your service!"
		buttonText  = "Show Me The Features!"


	# Service section
	[params.features]
		headline = "Some features you might like"

        [[params.features.list]]
            icon = "fa-hand-pointer-o"
            title = "Web Tooling"
            description = "The tooling is all web based - no need for an IDE or download."

		[[params.features.list]]
            icon = "fa-globe"
            title = "OpenAPI Based"
            description = "Formerly known as Swagger, the [OpenAPI](http://www.openapi.org) spec is fast becoming a standard."

        [[params.features.list]]
            icon = "fa-puzzle-piece"
			title = "Guided Design"
			description = "Even though it's based on OpenAPI, you don't need to know the spec!"

        [[params.features.list]]
            icon = "fa-code"
            title = "Embeddable"
            description = "Use the API Designer component in your own projects (and help us make it better)!"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Give it a try now..."

		[params.aside.button]
			text = "Try it!"
			link = "http://www.github.com/apiman/apiman-studio"

	# Contact section
	[params.contact]
		headline = "Let's get in touch!"
		description = "Ready to help us out to make the API Design Studio better?  Have some great ideas you can't help but share?  Great!  Here are some ways you can get in touch with us!"
		irc = "irc.freenode.net#apiman"
		email = "https://lists.jboss.org/mailman/listinfo/apiman-user"
		bugs = "https://issues.jboss.org/projects/APIMAN"
